export const ROUTES = {
  LAYOUT: '/',
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  LIBRARY: '/library',
  LIBRARY_CREATE: '/library-create',
  BOOK_CREATE: '/book-create',
  BOARD: '/board',
  ONBOARDING: '/onboarding',
  SETTING: '/mypage',
  SETTING_EDIT: '/mypage/edit',
  PRIVACY: '/privacy',
  TERMS_OR_SERVICE: '/terms-of-service',
  CHAT: '/chat',
  CHAT_ROOM: (id = ':matchId') => `/chat/${id}`,
  SCAN: '/scan',
  CART: '/cart',
  NOTIFICATION: '/notification',
  RESERVATION: '/reservation',
  RENTAL: '/rental',
  GROUP: '/group',
  BOOK_DETAIL: (id = ':bookId') => `/book/${id}`,
  LIBRARY_DETAIL: (id = ':libraryId') => `/library/${id}`,
  LIBRARY_BOOK: (id = ':libraryId') => `/library/${id}/book`,
  LIBRARY_REVIEW: (id = ':libraryId') => `/library/${id}/review`,
  REVIEW_CREATE: (id = ':Id') => `/review-create/${id}`,
};
