export const ROUTES = {
  LAYOUT: '/',
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  LIBRARY: '/library',
  LIBRARY_CREATE: '/library-create',
  BOOK_CREATE: '/book-create',
  BOARD: '/board',
  ONBOARDING: '/onboarding',
  SETTING: '/mypage',
  SETTING_EDIT: '/mypage/edit',
  CHAT: '/chat',
  CHAT_ROOM: (id = ':matchId') => `/chat/${id}`,
  SCAN: '/scan',
  CART: '/cart',
  NOTIFICATION: '/notification',
  MY_RESERVATION: '/mypage/reservation',
  MY_LOAN: '/mypage/loan',
  MY_GROUP: '/mypage/group',
};
