export const ROUTES = {
  LAYOUT: '/',
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  LIBRARY: '/library',
  LIBRARY_CREATE: '/library-create',
  BOOK_CREATE: '/book-create',
  BOARD: '/board',
  ONBOARDING: '/onboarding',
  SETTING: '/mypage',
  SETTING_EDIT: '/mypage/edit',
  CHAT: '/chat',
  CHAT_ROOM: (id = ':matchId') => `/chat/${id}`,
  SCAN: '/scan',
  CART: '/cart',
  NOTIFICATION: '/notification',
  RESERVATION: '/reservation',
  RENTAL: '/rental',
  GROUP: '/group',
  BOOK_DETAIL: (id = ':bookId') => `/book/${id}`,
  LIBRARY_DETAIL: (id = ':libraryId') => `/library/${id}`,
};
